#!/usr/bin/env python3
"""
session_context_blast.py — Dynamic session context loader for HALE staying time.

Runs at session start (or on demand). Queries Qdrant for context relevant
to active missions + projects, then writes a concise brief to
OpsCenter/session_context_latest.md so every Claude Code session loads
project-aware context instead of the same stale MEMORY.md.

Usage:
  python3 core/memory/session_context_blast.py
  python3 core/memory/session_context_blast.py --query "Kuklinski dining"
  python3 core/memory/session_context_blast.py --top-missions 10

Auto-triggered by: auto_session_monitor.sh (on session start detection)
Output: OpsCenter/session_context_latest.md (@ auto-loaded in CLAUDE.md)
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
THUNDERBIRD = Path(__file__).resolve().parent.parent.parent
MISSION_BOARD = THUNDERBIRD / "OpsCenter" / "mission_board.json"
HALE_STATE = THUNDERBIRD / "hale_state.json"
OUTPUT = THUNDERBIRD / "OpsCenter" / "session_context_latest.md"
COLLECTION = "thunderbird_memories"
QDRANT_URL = "http://localhost:6333"
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"


def _qdrant_up() -> bool:
    try:
        import requests
        r = requests.get(f"{QDRANT_URL}/collections", timeout=2)
        return r.status_code == 200
    except Exception:
        return False


def _get_active_missions(top_n: int = 8) -> list[dict]:
    """Return top P0/P1 active missions sorted by priority."""
    try:
        d = json.loads(MISSION_BOARD.read_text())
        missions = d.get("missions", []) + d.get("tasks", [])
        active = [
            m for m in missions
            if m.get("status", "") in ("active", "in_progress", "pending")
        ]
        priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
        active.sort(key=lambda m: priority_order.get(m.get("priority", "P3"), 4))
        return active[:top_n]
    except Exception:
        return []


def _get_active_projects() -> list[dict]:
    """Return active projects from hale_state.json project_tracking."""
    try:
        d = json.loads(HALE_STATE.read_text())
        tracking = d.get("project_tracking", {})
        projects = tracking.get("active_projects", [])
        return [p for p in projects if p.get("status") not in ("COMPLETE", "ARCHIVED")]
    except Exception:
        return []


def _get_wf17_items() -> list[dict]:
    """Return items sitting at WF-17 gate from hale_state.json."""
    try:
        d = json.loads(HALE_STATE.read_text())
        # Scan open_tasks and project_tracking for WF17_GATE items
        projects = d.get("project_tracking", {}).get("active_projects", [])
        return [p for p in projects if p.get("status") == "WF17_GATE"]
    except Exception:
        return []


def _semantic_search(queries: list[str], top_k: int = 4) -> list[dict]:
    """Run semantic search over Qdrant for given queries. Returns deduped results."""
    try:
        from fastembed import TextEmbedding
        from qdrant_client import QdrantClient

        client = QdrantClient(url=QDRANT_URL)
        embedder = TextEmbedding(EMBEDDING_MODEL)

        seen_files = set()
        results = []

        for query in queries:
            vecs = list(embedder.embed([query]))
            hits = client.search(COLLECTION, query_vector=vecs[0].tolist(), limit=top_k)
            for hit in hits:
                if not hit.payload:
                    continue
                fname = hit.payload.get("filename", "")
                if fname in seen_files:
                    continue
                seen_files.add(fname)
                results.append({
                    "filename": fname,
                    "filepath": hit.payload.get("filepath", ""),
                    "content": hit.payload.get("content", "")[:300],
                    "score": round(hit.score, 3),
                    "query": query,
                })

        return results
    except Exception as e:
        return [{"error": str(e)}]


def _financial_pulse(hale_state: dict) -> str:
    fp = hale_state.get("financial_pulse", {})
    if not fp:
        return ""
    return (
        f"Pipeline: ${fp.get('pipeline_d2m_share_upcoming', 0):,.2f} "
        f"across {fp.get('sheet_upcoming_count', 0)} voyages | "
        f"Commission expected: ${fp.get('sheet_commission_expected', 0):,.2f}"
    )


def generate_blast(top_missions: int = 8, extra_queries: list[str] | None = None) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# SESSION CONTEXT — {ts}",
        "*Auto-generated by session_context_blast.py — loaded at session start*",
        "*Replaces stale MEMORY.md auto-load with dynamic project-aware context.*",
        "",
    ]

    # ── 1. Active missions ───────────────────────────────────────────────────
    missions = _get_active_missions(top_missions)
    if missions:
        lines += ["## ACTIVE MISSIONS (P0/P1)", ""]
        for m in missions:
            title = m.get("title", "Untitled")[:70]
            status = m.get("status", "?")
            priority = m.get("priority", "?")
            mid = m.get("id", "?")
            notes = m.get("notes", m.get("description", ""))[:100]
            lines.append(f"- **{mid}** [{priority}/{status}] {title}")
            if notes:
                lines.append(f"  _{notes}_")
        lines.append("")

    # ── 2. Active projects ───────────────────────────────────────────────────
    projects = _get_active_projects()
    wf17 = _get_wf17_items()
    if projects or wf17:
        lines += ["## PROJECT TRACKING", ""]
        for p in projects:
            status = p.get("status", "?")
            name = p.get("name", "?")
            deadline = p.get("deadline", "")
            notes = p.get("notes", "")[:80]
            flag = " **[WF17 — COMMANDER GATE]**" if status == "WF17_GATE" else ""
            deadline_str = f" · due {deadline}" if deadline else ""
            lines.append(f"- **{name}** [{status}{deadline_str}]{flag}")
            if notes:
                lines.append(f"  _{notes}_")
        lines.append("")

    # ── 3. Financial pulse ───────────────────────────────────────────────────
    try:
        hale_state = json.loads(HALE_STATE.read_text())
        fp_line = _financial_pulse(hale_state)
        if fp_line:
            lines += ["## FINANCIAL PULSE", fp_line, ""]
    except Exception:
        pass

    # ── 4. Semantic memory search ────────────────────────────────────────────
    if _qdrant_up():
        # Build queries from active missions + any extra
        queries = []
        for m in missions[:5]:
            title = m.get("title", "")
            if title:
                queries.append(title)
        if extra_queries:
            queries.extend(extra_queries)

        if queries:
            results = _semantic_search(queries, top_k=3)
            useful = [r for r in results if "error" not in r and r.get("score", 0) > 0.3]
            if useful:
                lines += ["## RELEVANT MEMORY CONTEXT (Qdrant)", ""]
                for r in useful[:6]:
                    lines.append(f"**{r['filename']}** (score {r['score']}, query: _{r['query']}_)")
                    snippet = r["content"].replace("\n", " ").strip()[:200]
                    lines.append(f"> {snippet}")
                    lines.append("")
    else:
        lines += ["## QDRANT STATUS", "DOWN — semantic search unavailable.", ""]

    lines += [
        "---",
        f"*Generated: {ts} · Source: mission_board.json + hale_state.json + Qdrant*",
    ]
    return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate session context blast")
    parser.add_argument("--top-missions", type=int, default=8)
    parser.add_argument("--query", nargs="*", help="Extra semantic queries")
    parser.add_argument("--stdout", action="store_true", help="Print instead of writing file")
    args = parser.parse_args()

    blast = generate_blast(top_missions=args.top_missions, extra_queries=args.query)

    if args.stdout:
        print(blast)
    else:
        OUTPUT.write_text(blast)
        print(f"[session_context_blast] Written to {OUTPUT}")
        print(f"[session_context_blast] {blast.count(chr(10))} lines, {len(blast)} chars")


if __name__ == "__main__":
    main()
