"""Mission Auto-Executor — Hale's initiative engine.

Runs at session open (via hooks/session_open.sh → SessionStart hook).

Three passes:
  1. AUTO-CLOSE: missions whose notes/description signal completion but status is still open
  2. CLASSIFY: partition active missions into WING_EXECUTE / COMMANDER_REQUIRED / HOLD
  3. REPORT: write session_open_report.md with the day's action queue

Execution authority: SO-AUTONOMY / Production-Lock Retired 2026-06-10.
Commander gates (client-send, financial, strategic) respected.
"""

import json
import re
from datetime import datetime, date, timezone

UTC = timezone.utc
from pathlib import Path

BOARD_PATH = Path(__file__).parent / "mission_board.json"
REPORT_PATH = Path(__file__).parent.parent / "session_open_report.md"
HALE_STATE_PATH = Path(__file__).parent.parent / "hale_state.json"

# Signals in title/description/notes that mean Commander must act
COMMANDER_SIGNALS = [
    r"\bcall\b",          # "Call Atlas Voyages", "Commander calls"
    r"\bbook\b",          # "Book DEN-GRB", "Book Regent"
    r"commander (?:to|calls|must|action)",
    r"manual .{0,20}(?:re-?auth|login|log in|firefox|browser)",
    r"commander to confirm",
    r"contact perx",
    r"yoga firefox",
]

# Signals in notes that mean the work is already done
DONE_SIGNALS = [
    r"^complete",
    r"satisfied \d{4}-\d{2}-\d{2}",
    r"✅.{0,20}complete",
    r"complete —",
]

# Keywords that indicate date-gated holds
HOLD_SIGNALS = [
    r"hold until",
    r"do not contact until",
    r"hold.*jul",
    r"activate jul",
    r"deferred",
]


def _text(m: dict) -> str:
    """Concatenate all text fields for pattern matching (gate/hold classification)."""
    return " ".join([
        (m.get("title") or ""),
        (m.get("description") or ""),
        (m.get("notes") or ""),
    ]).lower()


def _notes_only(m: dict) -> str:
    """Notes field only — used for done-signal matching to avoid false positives."""
    return (m.get("notes") or "").lower()


def _is_done(m: dict) -> bool:
    # Only check notes field — descriptions often contain "complete" as context
    t = _notes_only(m)
    return bool(t) and any(re.search(p, t) for p in DONE_SIGNALS)


def _is_commander_required(m: dict) -> bool:
    t = _text(m)
    return any(re.search(p, t) for p in COMMANDER_SIGNALS)


def _is_hold(m: dict) -> bool:
    t = _text(m)
    return any(re.search(p, t) for p in HOLD_SIGNALS)


def classify_missions(missions: list) -> dict:
    active = [m for m in missions if m.get("status") in ("active", "open", "in_progress")]

    auto_close = []
    commander_queue = []
    wing_execute = []
    hold_items = []

    for m in active:
        if _is_done(m):
            auto_close.append(m)
        elif _is_hold(m):
            hold_items.append(m)
        elif _is_commander_required(m):
            commander_queue.append(m)
        else:
            wing_execute.append(m)

    return {
        "auto_close": auto_close,
        "commander_queue": commander_queue,
        "wing_execute": wing_execute,
        "hold_items": hold_items,
    }


def apply_auto_close(missions: list, auto_close_candidates: list[dict]) -> int:
    """Mark auto-close missions as 'complete' — matched by object identity, not just ID.

    Uses 'is' comparison to avoid closing duplicate-ID entries that didn't pass done check.
    """
    candidate_set = {id(m) for m in auto_close_candidates}
    closed = 0
    for m in missions:
        if id(m) in candidate_set:
            m["status"] = "complete"
            m["closed_at"] = datetime.now(UTC).isoformat()
            m["closed_by"] = "mission_auto_executor"
            closed += 1
    return closed


def load_deferred_alerts() -> list:
    """Pull date-triggered deferred items from hale_state.json."""
    try:
        state = json.loads(HALE_STATE_PATH.read_text())
        alerts = state.get("deferred_alerts", [])
        today = date.today().isoformat()
        due = [a for a in alerts if a.get("trigger_date", "9999") <= today]
        upcoming = [a for a in alerts if today < a.get("trigger_date", "9999") <= "2026-07-31"]
        return {"due_now": due, "upcoming_30d": upcoming}
    except Exception:
        return {"due_now": [], "upcoming_30d": []}


def write_report(classified: dict, auto_closed: int, deferred: dict, now: str) -> str:
    lines = [
        f"# SESSION OPEN REPORT — {now}",
        f"*Generated by mission_auto_executor.py*",
        "",
    ]

    if auto_closed:
        lines += [
            f"## ✅ AUTO-CLOSED ({auto_closed} missions)",
            "",
        ]
        for m in classified["auto_close"]:
            lines.append(f"- **{m['id']}** — {m.get('title','')[:70]}")
        lines.append("")

    # Deferred alerts due now
    if deferred["due_now"]:
        lines += ["## 🔴 DEFERRED ALERTS — DUE NOW", ""]
        for a in deferred["due_now"]:
            lines.append(f"- **{a.get('id','')}** — {a.get('message','')[:100]}")
        lines.append("")

    # Commander action queue — P0s first
    cq = classified["commander_queue"]
    if cq:
        p0 = [m for m in cq if m.get("priority") == "P0"]
        p1 = [m for m in cq if m.get("priority") == "P1"]
        rest = [m for m in cq if m.get("priority") not in ("P0", "P1")]
        lines += [f"## 🎯 COMMANDER ACTION QUEUE ({len(cq)} items)", ""]
        for m in (p0 + p1 + rest):
            pri = m.get("priority", "?")
            lines.append(f"- [{pri}] **{m['id']}** — {m.get('title','')[:70]}")
        lines.append("")

    # Wing-executable
    we = classified["wing_execute"]
    if we:
        p0 = [m for m in we if m.get("priority") == "P0"]
        p1 = [m for m in we if m.get("priority") == "P1"]
        rest = [m for m in we if m.get("priority") not in ("P0", "P1")]
        lines += [f"## 🦅 WING EXECUTABLE ({len(we)} missions — no Commander gate)", ""]
        for m in (p0 + p1 + rest):
            pri = m.get("priority", "?")
            lines.append(f"- [{pri}] **{m['id']}** — {m.get('title','')[:70]}")
        lines.append("")

    # Holds
    ho = classified["hold_items"]
    if ho:
        lines += [f"## ⏸ ON HOLD ({len(ho)} items — date-gated)", ""]
        for m in ho:
            lines.append(f"- **{m['id']}** — {m.get('title','')[:70]}")
        lines.append("")

    # Upcoming 30d deferred
    if deferred["upcoming_30d"]:
        lines += ["## 📅 UPCOMING TRIGGERS (30d)", ""]
        for a in deferred["upcoming_30d"]:
            lines.append(f"- **{a.get('trigger_date','')}** {a.get('id','')} — {a.get('message','')[:80]}")
        lines.append("")

    report = "\n".join(lines)
    REPORT_PATH.write_text(report)
    return report


def run() -> dict:
    data = json.loads(BOARD_PATH.read_text())
    missions = data.get("missions", data.get("tasks", []))

    classified = classify_missions(missions)

    # Apply auto-closes — pass candidate objects directly (object identity, avoids dup-ID collateral)
    auto_closed = apply_auto_close(missions, classified["auto_close"])

    if auto_closed:
        BOARD_PATH.write_text(json.dumps(data, indent=2))

    deferred = load_deferred_alerts()
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    report = write_report(classified, auto_closed, deferred, now)

    return {
        "auto_closed": auto_closed,
        "commander_queue": len(classified["commander_queue"]),
        "wing_executable": len(classified["wing_execute"]),
        "holds": len(classified["hold_items"]),
        "report_path": str(REPORT_PATH),
    }


if __name__ == "__main__":
    result = run()
    print(f"✅ auto-closed: {result['auto_closed']}")
    print(f"🎯 Commander queue: {result['commander_queue']}")
    print(f"🦅 Wing executable: {result['wing_executable']}")
    print(f"⏸ Holds: {result['holds']}")
    print(f"📄 Report: {result['report_path']}")
