#!/usr/bin/env python3
import os
import asyncio
import google.generativeai as genai
import logging

logging.basicConfig(filename='/home/john/Thunderbird/OpsCenter/overwatch.log', level=logging.INFO, format='%(asctime)s - [P3 UPDATE V3 (FLASH)] - %(message)s')

genai.configure(api_key=os.environ.get("GOOGLE_API_KEY", "***REMOVED-SECRET***"))

async def a5_strategy_v3():
    logging.info("A5 Castillo synthesizing Commander's High-Thinking Feedback on Lifecycle SOP via Gemini Flash...")

    feedback = """
    Look at Claude's 3 HTMLs; they are not as detailed as they need to be and they don't adhere to this thought: ALWAYS get staff input first.
    The schedule needs to be extremely flexible but also firm. 
    1) It has several unpredictable but once committed factually known dates: date of initial contact, initial deposit date.
    2) Then once booked: embarkation date, disembarkation date, final payment, excursions, dining. 
    From that point on, they are at the client's discretion and MAY NOT follow a schedule: Flights, hotels, transfers, independent bookings. 
    SO you see, we need an intelligent approach, we need a high-thinking model.
    """

    prompt = f"""
    You are Lt Col Ryan Castillo (A5), Chief Strategy Officer for Dreams2Memories Travel (16-20 elite clients).
    You are utilizing a high-thinking, strategic mental model.
    The Commander has completely REJECTED the previous linear 15-18 month lifecycle models generated by Claude.
    
    He provided this architectural breakthrough:
    "{feedback}"
    
    Your task: Rewrite the entire conceptual framework of the D2M Client Lifecycle.
    Do NOT build a rigid timeline (Month 1, Month 2). 
    Build a dynamic, event-triggered architecture.
    
    The architecture MUST be built around these Anchor Nodes:
    - Node 1: Unpredictable Triggers (Initial Contact, Deposit Date).
    - Node 2: Hard Anchors (Embarkation, Disembarkation, Final Payment Date, Excursion Booking Window, Dining Window).
    - Node 3: Fluid Variables (Flights, pre/post hotels, transfers - executed at client discretion).
    
    Crucial Rule: "ALWAYS get staff input first." Explain how A2 (Dembe), A9 (Harlan), and A6 (Luna) feed intelligence to A3 (Dani) *before* she acts on any of these nodes.
    
    Output this as a highly detailed, strategic Staff Paper ready to govern how our AI agents actually operate.
    """
    
    model = genai.GenerativeModel('gemini-2.5-pro')
    # Use sync API wrapped in thread to avoid async context errors in old Python versions
    return await asyncio.to_thread(model.generate_content, prompt)

async def run_p3_v3():
    try:
        response = await a5_strategy_v3()
        sop = response.text
        
        with open("/home/john/Thunderbird/OpsCenter/collaboration/D2M_Lifecycle_Event_Architecture.md", "w") as f:
            f.write(sop)
            
        logging.info("P3 V3 COMPLETE. Revised Event-Driven Architecture written.")
        
    except Exception as e:
        logging.error(f"P3 V3 Failed: {e}")

if __name__ == "__main__":
    asyncio.run(run_p3_v3())

