use_default_settings: true
server:
  secret_key: "3265d76e8092ec3ffc922f52a8c35c555d82b97976e237ddf5b90aec130278fa"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
search:
  formats:
    - html
    - json
