#!/bin/bash
# Auto-save checkpoint routine — fires every 10 minutes
# Writes session state to session_autosave_latest.md
# Part of Hale COS Standing Order: Auto-Save Protocol (2026-03-27)

CHECKPOINT_FILE="/home/john/Thunderbird/session_autosave_latest.md"
INBOX_CLAUDE="/home/john/Thunderbird/claude_inbox.md"
INBOX_OPENCODE="/home/john/Thunderbird/OpsCenter/collaboration/opencode_inbox.md"
GIT_DIR="/home/john/Thunderbird"

# Build checkpoint
{
    echo "# Thunderbird Session Checkpoint"
    echo "## Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo ""
    echo "---"
    echo ""

    echo "### Recent Commits"
    cd "$GIT_DIR" && git log --oneline -5 | sed 's/^/- /'
    echo ""

    echo "### Uncommitted Changes"
    cd "$GIT_DIR" && git status -s | head -20
    echo ""

    # Count pending tasks
    CLAUDE_PENDING=$(grep -c "status: PENDING\|status: UNREAD\|status: ACTIVE-CRITICAL\|status: FLAGGED-OVERDUE" "$INBOX_CLAUDE" 2>/dev/null || echo 0)
    OPENCODE_PENDING=$(grep -c "status: PENDING\|status: UNREAD\|status: ACTIVE-CRITICAL\|status: FLAGGED-OVERDUE" "$INBOX_OPENCODE" 2>/dev/null || echo 0)

    echo "### Inbox Status"
    echo "- Claude inbox: $CLAUDE_PENDING pending task(s)"
    echo "- OpenCode inbox: $OPENCODE_PENDING pending task(s)"
    echo ""

    # System health (basic check)
    echo "### System Health"
    if systemctl is-active --quiet d2m-tasking-watcher; then
        echo "- Watcher: ✅ RUNNING"
    else
        echo "- Watcher: ❌ STOPPED"
    fi

    if pgrep -f "claude.*-p" > /dev/null; then
        echo "- Claude headless: ✅ ACTIVE"
    else
        echo "- Claude headless: ⏸ idle"
    fi

    if pgrep -f "opencode" > /dev/null; then
        echo "- OpenCode headless: ✅ ACTIVE"
    else
        echo "- OpenCode headless: ⏸ idle"
    fi
    echo ""

    echo "---"
    echo "*Auto-generated by COS · Thunderbird OS · Auto-Save Protocol 2026-03-27*"
} > "$CHECKPOINT_FILE"

exit 0
