#!/usr/bin/env python3
"""
correction_capture.py — Thunderbird Wing | A7 Sterling | 2026-06-04

PURPOSE: Capture a verbal Commander correction to disk AND patch the client dossier.
Called the moment Hale receives any correction from Commander — before ANY agent spawn.

USAGE:
    python3 scripts/correction_capture.py --client "Ely" --correction "At Six both nights, eliminate insurance"
    python3 scripts/correction_capture.py --client "Nichols" --correction "CFAR dropped, At Six Night 1 deferred"

OUTPUT:
    - Appends correction to corrections/{client}_corrections.md (audit trail, never overwrites)
    - Patches dossier with an idempotent LIVE CORRECTIONS section (regenerated each run)
    - Prints: [OK] Correction captured + dossier patched: {client}

METRIC: Every correction that exits this script is on disk before any agent is spawned.
OWNER: Sterling (A7)
"""

import argparse
import glob
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


# ── Path resolution (always relative to repo root, never cwd) ──────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
CORRECTIONS_DIR = REPO_ROOT / "corrections"
DOSSIERS_DIR = REPO_ROOT / "dossiers"

# Filename patterns to exclude from dossier glob (supplemental / backup files)
EXCLUDE_PATTERNS = [".bak", "_Coverage_Brief", "_Tips_Guide", "DOSSIER_", "prospects/"]


def find_dossier(client: str) -> Path | None:
    """
    Locate the primary dossier for a client.

    Preference order:
      1. Files matching *{client}*.md (case-insensitive), excluding supplemental/backup files
      2. If multiple remain: prefer the shortest filename (most specific) and exclude DOSSIER_ prefixes
      3. If still ambiguous: fail loud — do not pick arbitrarily

    Returns Path or None.
    """
    pattern = str(DOSSIERS_DIR / "*.md")
    all_md = glob.glob(pattern)

    # Filter to files containing the client name (case-insensitive), excluding known noise
    candidates = []
    for filepath in all_md:
        fname = os.path.basename(filepath)
        if client.lower() not in fname.lower():
            continue
        skip = False
        for excl in EXCLUDE_PATTERNS:
            if excl in fname:
                skip = True
                break
        if not skip:
            candidates.append(Path(filepath))

    if not candidates:
        return None

    if len(candidates) == 1:
        return candidates[0]

    # Multiple matches — prefer exact booking dossiers (contain a digit booking ref)
    # and prefer shorter filenames (less qualified = more likely the primary)
    booking_candidates = [c for c in candidates if re.search(r"\d{5,}", c.name)]
    if len(booking_candidates) == 1:
        return booking_candidates[0]

    # Still ambiguous — fail loud
    names = [c.name for c in candidates]
    print(f"[ERROR] Ambiguous dossier match for '{client}': {names}", file=sys.stderr)
    print(f"        Specify a more unique client name or resolve ambiguity manually.", file=sys.stderr)
    return None


def load_all_corrections(corrections_file: Path) -> list[str]:
    """
    Parse the corrections file and return a list of raw correction text lines.
    Skips separator lines, blank lines, and timestamp header lines.
    """
    if not corrections_file.exists():
        return []

    corrections = []
    with open(corrections_file, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            # Skip blank, separator, and header lines
            if not stripped:
                continue
            if stripped.startswith("---"):
                continue
            if stripped.startswith("## CORRECTION"):
                continue
            if stripped.startswith("**Captured:**"):
                continue
            if stripped.startswith("**Text:**"):
                # Extract the correction text after "**Text:** "
                text = stripped.replace("**Text:**", "").strip()
                if text:
                    corrections.append(text)
    return corrections


def build_live_corrections_block(corrections: list[str], client: str) -> str:
    """Build the LIVE CORRECTIONS section text to inject into the dossier."""
    lines = ["", "## LIVE CORRECTIONS", ""]
    lines.append("> Generated by correction_capture.py — do not edit manually.")
    lines.append("> This section is regenerated on each correction_capture.py run.")
    lines.append("> THESE CORRECTIONS OVERRIDE DOSSIER DATA WHERE THEY CONFLICT.")
    lines.append("")
    for i, c in enumerate(corrections, 1):
        lines.append(f"{i}. {c}")
    lines.append("")
    return "\n".join(lines)


def patch_dossier(dossier_path: Path, corrections: list[str], client: str) -> bool:
    """
    Idempotently update the LIVE CORRECTIONS section in the dossier.
    Replaces any existing LIVE CORRECTIONS block rather than appending.
    Returns True on success.
    """
    content = dossier_path.read_text(encoding="utf-8")

    new_block = build_live_corrections_block(corrections, client)

    # Pattern to match existing LIVE CORRECTIONS block (from header to next ## or EOF)
    live_section_pattern = re.compile(
        r"\n## LIVE CORRECTIONS\n.*?(?=\n## |\Z)",
        re.DOTALL,
    )

    if live_section_pattern.search(content):
        # Replace existing block
        updated = live_section_pattern.sub(new_block, content)
    else:
        # Append at end of file
        updated = content.rstrip() + "\n" + new_block

    dossier_path.write_text(updated, encoding="utf-8")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Capture a Commander correction to disk and patch the client dossier."
    )
    parser.add_argument(
        "--client", required=True, help="Client name (e.g., Ely, Nichols, Furlow)"
    )
    parser.add_argument(
        "--correction",
        required=True,
        help='Correction text (e.g., "At Six both nights, eliminate insurance")',
    )
    args = parser.parse_args()

    client = args.client.strip()
    correction_text = args.correction.strip()

    # ── 1. Ensure corrections dir exists ──────────────────────────────────────
    CORRECTIONS_DIR.mkdir(parents=True, exist_ok=True)

    # ── 2. Append to corrections file (audit trail) ───────────────────────────
    corrections_file = CORRECTIONS_DIR / f"{client}_corrections.md"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    entry = (
        f"\n## CORRECTION — {ts}\n"
        f"**Captured:** {ts}\n"
        f"**Text:** {correction_text}\n"
        f"---\n"
    )

    with open(corrections_file, "a", encoding="utf-8") as f:
        if corrections_file.stat().st_size == 0 if corrections_file.exists() else True:
            # Write header if brand new file or first write
            pass
        f.write(entry)

    print(f"[OK] Correction written: {corrections_file.relative_to(REPO_ROOT)}")

    # ── 3. Load all corrections for this client ───────────────────────────────
    all_corrections = load_all_corrections(corrections_file)

    # ── 4. Find and patch the dossier ─────────────────────────────────────────
    dossier = find_dossier(client)
    if dossier is None:
        print(
            f"[WARN] No dossier found for '{client}' — correction written to file only.",
            file=sys.stderr,
        )
        print(f"[OK] Correction captured (dossier NOT patched — not found): {client}")
        return

    if not patch_dossier(dossier, all_corrections, client):
        print(f"[ERROR] Failed to patch dossier: {dossier}", file=sys.stderr)
        sys.exit(1)

    print(f"[OK] Dossier patched: {dossier.relative_to(REPO_ROOT)}")
    print(f"[OK] Correction captured + dossier patched: {client}")
    print(f"     Total corrections on file: {len(all_corrections)}")
    print(f"     Latest: {correction_text}")


if __name__ == "__main__":
    main()
