#!/usr/bin/env python3
"""
Send sonnet review email to d2mconcierge
To be executed when sonnet review is complete
"""
import os
from pathlib import Path

def create_email_draft(review_file_path):
    """Create HTML email draft with sonnet review content"""
    
    # Read the completed review
    if not os.path.exists(review_file_path):
        print(f"Error: Review file not found at {review_file_path}")
        return False
    
    try:
        with open(review_file_path, 'r') as f:
            review_content = f.read()
    except Exception as e:
        print(f"Error reading review file: {e}")
        return False
    
    # Create HTML email with embedded review
    email_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SONNET REVIEW: Claude Code Enhancements Analysis — COMPLETE</title>
    <style>
        body {{ font-family: Georgia, serif; background-color: #f7f3ea; color: #000; margin: 20px; }}
        .content {{ max-width: 900px; margin: 0 auto; background: white; padding: 30px; border: 1px solid #ddd; }}
        h1 {{ color: #0000ff; border-bottom: 2px solid #0000ff; padding-bottom: 10px; }}
        h2 {{ color: #0000cc; margin-top: 25px; }}
        h3 {{ color: #000099; margin-top: 20px; }}
        .status {{ background: #d4edda; border: 1px solid #c3e6cb; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
        th {{ background-color: #f8f9fa; }}
        .highlight {{ background: #e8f4fd; padding: 15px; border-radius: 5px; margin: 15px 0; }}
    </style>
</head>
<body>
    <div class="content">
        <h1>✅ SONNET-MODEL REVIEW: Claude Code Enhancements Analysis</h1>
        
        <div class="status">
            <strong>🏁 STATUS:</strong> <span style="color: #28a745;">COMPLETED</span><br>
            <strong>📅 Completed:</strong> 2026-04-24<br>
            <strong>📊 Analysis Scope:</strong> 20+ enhancements across Thunderbird OS
        </div>

        <div class="highlight">
            <h2>📋 Executive Summary</h2>
            <p>Comprehensive sonnet-model review of Claude Code enhancements to our multi-model stack. 
            Analysis includes impact scoring, technical maturity assessment, and strategic recommendations.</p>
        </div>

        <h2>📈 Full Analysis Report</h2>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0;">
            <pre style="white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 12px; line-height: 1.4;">
{review_content}
            </pre>
        </div>

        <h2>📁 Additional Access</h2>
        <p><strong>Original file location:</strong> <code>{review_file_path}</code></p>
        <p><strong>SSH access:</strong></p>
        <pre>ssh john@192.168.1.198
cd /home/john/Thunderbird/output/
cat sonnet_review_*.md</pre>

        <hr>
        
        <p style="color: #666; font-style: italic;">
            This review was generated by Claude Sonnet 4.6 following Commander's directive for comprehensive
            analysis of Claude Code enhancements to the Thunderbird OS multi-model stack.
        </p>
    </div>
</body>
</html>"""
    
    # Save email draft
    draft_path = "/home/john/Thunderbird/drafts/sonnet_review_complete.html"
    try:
        with open(draft_path, 'w') as f:
            f.write(email_content)
        print(f"Email draft created: {draft_path}")
        return True
    except Exception as e:
        print(f"Error creating email draft: {e}")
        return False

def main():
    # Find the latest sonnet review file
    output_dir = Path("/home/john/Thunderbird/output")
    review_files = list(output_dir.glob("sonnet_review_*.md"))
    
    if not review_files:
        print("No sonnet review files found in output directory")
        # Check if any are being created
        recent_files = list(output_dir.glob("*.md"))
        if recent_files:
            print(f"Found other files: {[f.name for f in recent_files]}")
        return
    
    # Use the most recent file
    latest_review = max(review_files, key=lambda x: x.stat().st_mtime)
    print(f"Found review file: {latest_review}")
    
    # Create email draft
    if create_email_draft(str(latest_review)):
        print("✅ Email draft created successfully")
        print("Location: /home/john/Thunderbird/drafts/sonnet_review_complete.html")
    else:
        print("❌ Failed to create email draft")

if __name__ == "__main__":
    main()