#!/usr/bin/env python3
"""
wing_org_compile.py — Thunderbird Wing Org Compiler
Reads config/wing_org.yaml and emits three outputs:
  1. CC seat files: update frontmatter model: + inject ## WING SEAT CONTRACT in .claude/agents/<file>.md
  2. OC agent blocks: config/opencode_agents.generated.json
  3. Brain bridge lane registry: config/wing_lanes.generated.json

ENFORCEMENT: pii:true + engine:oc → refuse, exit 1.

Authored 2026-07-02 | A7 Sterling | Pure stdlib + pyyaml
"""

import sys
import json
import re
import yaml
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).parent.parent
WING_ORG_YAML = REPO_ROOT / "config" / "wing_org.yaml"
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
OC_JSON_OUT = REPO_ROOT / "config" / "opencode_agents.generated.json"
LANES_JSON_OUT = REPO_ROOT / "config" / "wing_lanes.generated.json"

# HARD: never touch these files
PROTECTED_FILES = {
    REPO_ROOT / "core" / "email",
    REPO_ROOT / "core" / "relay",
    REPO_ROOT / "OpsCenter" / "relay_send.py",
    REPO_ROOT / "OpsCenter" / "dispatch_and_email.py",
    REPO_ROOT / "OpsCenter" / "email_task_ingest.py",
    REPO_ROOT / "OpsCenter" / "run_commander_directive_sweep.py",
}

# ---------------------------------------------------------------------------
# Seat → agent filename mapping (hardcoded: not derivable from config)
# ---------------------------------------------------------------------------
SEAT_TO_FILE = {
    "hale":      "cos-hale.md",
    "dembe":     "a2-dembe.md",
    "sterling":  "a7-sterling.md",
    "harlan":    "a9-harlan.md",
    "elon":      "a12-elon.md",
    "dani":      "a3-moreau.md",
    "luna":      "a6-voss.md",
    "naia":      "exec-solberg-vega.md",
    "ikeda":     "a10-ikeda.md",
    "reyes":     "a8-reyes.md",       # stub created 2026-07-02 — now seated
    "whetstone": "a14-whetstone.md",  # stub created 2026-07-02 — now seated
    "talon":     "talon.md",          # CONDOR wing commander (CC) — seated 2026-07-02
}

NO_FILE_SEATS = set()  # all declared CC seats now have files

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_yaml():
    with open(WING_ORG_YAML) as f:
        return yaml.safe_load(f)


def parse_frontmatter(text: str):
    """
    Split a markdown file into (frontmatter_dict, body_text).
    frontmatter_dict is None if no --- block found.
    body_text is everything after the closing ---.
    Returns (raw_frontmatter_lines, body_lines).
    """
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return None, lines

    # Find closing ---
    close_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            close_idx = i
            break

    if close_idx is None:
        return None, lines

    fm_lines = lines[1:close_idx]      # between the two ---
    body_lines = lines[close_idx + 1:] # after closing ---
    fm_dict = yaml.safe_load("".join(fm_lines)) or {}
    return fm_lines, body_lines


def rebuild_file(fm_lines: list, body_lines: list) -> str:
    return "---\n" + "".join(fm_lines) + "---\n" + "".join(body_lines)


def set_frontmatter_model(fm_lines: list, model: str) -> list:
    """
    Insert or update 'model: <value>' in frontmatter lines.
    Surgical: preserves all other keys and order.
    """
    model_pattern = re.compile(r"^model\s*:")
    new_line = f"model: {model}\n"

    for i, line in enumerate(fm_lines):
        if model_pattern.match(line):
            if fm_lines[i] == new_line:
                return fm_lines  # already correct, no change
            fm_lines = list(fm_lines)
            fm_lines[i] = new_line
            return fm_lines

    # Not present — append before end of fm_lines
    fm_lines = list(fm_lines)
    fm_lines.append(new_line)
    return fm_lines


CONTRACT_HEADING = "## WING SEAT CONTRACT"
CONTRACT_SENTINEL_RE = re.compile(r"^## WING SEAT CONTRACT\s*$", re.MULTILINE)


def build_contract_block(seat: str, seat_cfg: dict, banner: str) -> str:
    tools_note = ", ".join(seat_cfg.get("tools", []))
    lane = seat_cfg.get("lane", "unassigned")
    pii = seat_cfg.get("pii", False)
    engine = seat_cfg.get("engine", "cc")
    model = seat_cfg.get("model", "sonnet")

    block = (
        f"{CONTRACT_HEADING}\n"
        f"<!-- auto-generated by wing_org_compile.py — edit wing_org.yaml, not this block -->\n\n"
        f"**Seat:** {seat}  \n"
        f"**Engine:** {engine}  \n"
        f"**Model:** {model}  \n"
        f"**Lane:** {lane}  \n"
        f"**PII-cleared:** {str(pii).lower()}  \n"
        f"**Lane tools (label):** {tools_note}  \n\n"
        f"### Standing Banner (injected by compiler, non-negotiable)\n\n"
        f"{banner.rstrip()}\n"
    )
    return block


def upsert_contract(body_lines: list, seat: str, seat_cfg: dict, banner: str) -> list:
    """
    Idempotent: replace existing ## WING SEAT CONTRACT section or append it.
    """
    body_text = "".join(body_lines)
    new_block = build_contract_block(seat, seat_cfg, banner)

    match = CONTRACT_SENTINEL_RE.search(body_text)
    if match:
        # Replace from the heading to EOF (contract is always last section)
        # OR to the next ## heading if there's one after
        start = match.start()
        # Find the next h2 heading after our contract block
        after = body_text[match.end():]
        next_h2 = re.search(r"\n## ", after)
        if next_h2:
            end = match.end() + next_h2.start() + 1  # keep the \n before ##
        else:
            end = len(body_text)

        new_body = body_text[:start] + new_block + "\n"
        # If there was content after the contract block, re-attach it
        if next_h2:
            new_body = body_text[:start] + new_block + "\n" + body_text[end:]
    else:
        # Not present — append with a blank line separator
        stripped = body_text.rstrip("\n")
        new_body = stripped + "\n\n" + new_block + "\n"

    return new_body.splitlines(keepends=True)


# ---------------------------------------------------------------------------
# PII enforcement
# ---------------------------------------------------------------------------

def check_pii_enforcement(all_seats: dict):
    """
    Exit non-zero if any seat has pii:true AND engine:oc.
    all_seats: {seat_name: seat_cfg}
    """
    violations = []
    for seat, cfg in all_seats.items():
        if cfg.get("pii", False) and cfg.get("engine") == "oc":
            violations.append(seat)

    if violations:
        print(
            f"ERROR: PII ENFORCEMENT FAILED — PII seat must be CC engine.\n"
            f"  Violating seats: {', '.join(violations)}\n"
            f"  Fix wing_org.yaml: set engine:cc for these seats or set pii:false.",
            file=sys.stderr,
        )
        sys.exit(1)

    return len(all_seats)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=== WING ORG COMPILER — 2026-07-02 ===\n")

    # Load config
    org = load_yaml()
    banner: str = org.get("banner", "")
    if not banner:
        print("ERROR: No banner found in wing_org.yaml", file=sys.stderr)
        sys.exit(1)

    # Build unified seat list: lead + seats
    all_seats: dict = {}

    # Lead (hale) — special-case missing lane/pii
    lead_cfg = dict(org.get("lead", {}))
    lead_cfg.setdefault("lane", "lead")
    lead_cfg.setdefault("pii", False)
    all_seats["hale"] = lead_cfg

    # Regular seats
    for seat, cfg in org.get("seats", {}).items():
        all_seats[seat] = dict(cfg)

    # ---------- PII ENFORCEMENT ----------
    total_seats = check_pii_enforcement(all_seats)
    print(f"PII check: PASS (0 violations across {total_seats} seats)\n")

    # ---------- OUTPUT 1: CC seat files ----------
    cc_updated = []
    cc_skipped = []
    cc_no_file = []

    cc_seats = {k: v for k, v in all_seats.items() if v.get("engine") == "cc"}

    for seat, cfg in cc_seats.items():
        if seat in NO_FILE_SEATS:
            cc_no_file.append(seat)
            print(f"  [SKIP] {seat}: no agent file exists (no stub created)")
            continue

        filename = SEAT_TO_FILE.get(seat)
        if not filename:
            cc_no_file.append(seat)
            print(f"  [SKIP] {seat}: no file mapping in SEAT_TO_FILE")
            continue

        agent_path = AGENTS_DIR / filename

        # Verify no protected path collision (defensive)
        for prot in PROTECTED_FILES:
            if str(agent_path).startswith(str(prot)):
                print(f"  [GUARD] {seat}: {agent_path} is protected — skipped", file=sys.stderr)
                continue

        if not agent_path.exists():
            cc_no_file.append(seat)
            print(f"  [SKIP] {seat}: file not found at {agent_path}")
            continue

        original = agent_path.read_text(encoding="utf-8")
        fm_lines, body_lines = parse_frontmatter(original)

        if fm_lines is None:
            cc_skipped.append(seat)
            print(f"  [SKIP] {seat}: no YAML frontmatter block in {filename}")
            continue

        # Update model in frontmatter
        new_fm_lines = set_frontmatter_model(fm_lines, cfg.get("model", "sonnet"))

        # Upsert WING SEAT CONTRACT in body
        new_body_lines = upsert_contract(body_lines, seat, cfg, banner)

        new_text = rebuild_file(new_fm_lines, new_body_lines)

        if new_text != original:
            agent_path.write_text(new_text, encoding="utf-8")
            cc_updated.append(seat)
            print(f"  [UPDATED] {seat} → {filename}")
        else:
            cc_skipped.append(seat)
            print(f"  [NO-CHANGE] {seat} → {filename} (idempotent)")

    # ---------- OUTPUT 2: OC agent blocks ----------
    oc_seats = {k: v for k, v in all_seats.items() if v.get("engine") == "oc"}
    oc_output = {}
    for seat, cfg in oc_seats.items():
        oc_output[seat] = {
            "mode": "subagent",
            "model": cfg.get("model", "deepseek-v3.2"),
            "permission": "read-write-nopii",
        }

    OC_JSON_OUT.write_text(json.dumps(oc_output, indent=2) + "\n", encoding="utf-8")
    print(f"\n  [WRITTEN] {OC_JSON_OUT} ({len(oc_output)} OC seats)")

    # ---------- OUTPUT 3: Brain bridge lane registry ----------
    lanes_output = {}
    for seat, cfg in all_seats.items():
        lanes_output[seat] = {
            "engine": cfg.get("engine", "cc"),
            "lane": cfg.get("lane", "unassigned"),
            "pii": cfg.get("pii", False),
        }

    LANES_JSON_OUT.write_text(json.dumps(lanes_output, indent=2) + "\n", encoding="utf-8")
    print(f"  [WRITTEN] {LANES_JSON_OUT} ({len(lanes_output)} lanes)\n")

    # ---------- SUMMARY ----------
    print("=" * 50)
    print("SUMMARY")
    print("=" * 50)
    print(f"  Total seats declared:  {total_seats}")
    print(f"  CC seats processed:    {len(cc_seats)}")
    print(f"    Updated (changed):   {len(cc_updated)} → {cc_updated}")
    print(f"    No-change (idem):    {len(cc_skipped)} → {cc_skipped}")
    print(f"    Skipped (no file):   {len(cc_no_file)} → {cc_no_file}")
    print(f"  OC seats compiled:     {len(oc_output)} → {list(oc_output.keys())}")
    print(f"  PII enforcement:       PASS (0 violations)")
    print(f"\n  Files written:")
    print(f"    {OC_JSON_OUT}")
    print(f"    {LANES_JSON_OUT}")
    for seat in cc_updated:
        filename = SEAT_TO_FILE.get(seat, "?")
        print(f"    {AGENTS_DIR / filename}")
    print("\n  Protected files: NOT TOUCHED")
    print("=" * 50)


if __name__ == "__main__":
    main()
